import React from "react";

const RightToLeftBannerLight: React.FC = () => {
  const textContent =
    "WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED * WRAP YOUR DATA * CHAT WRAPPED *";
  return (
    <div className="w-screen overflow-hidden">
      <style>
        {`
          @keyframes marquee {
            from { transform: translateX(0); }
            to { transform: translateX(-33.3333%); }
          }

          @keyframes marquee-reverse {
            from { transform: translateX(-33.3333%); }
            to { transform: translateX(0); }
          }

          .marquee-container {
            display: flex;
            white-space: nowrap;
            width: 300%;
          }

          .animate-marquee {
            animation: marquee 10s linear infinite;
          }

          .animate-marquee-reverse {
            animation: marquee-reverse 10s linear infinite;
          }
        `}
      </style>

      {/* Left to Right */}
      <div className="w-full border-2 border-primary2  py-3 overflow-hidden mt-1">
        <div className="marquee-container animate-marquee-reverse p-5">
          {[...Array(3)].map((_, i) => (
            <span
              key={i}
              className="text-primary2 font-mono text-lg min-w-screen"
            >
              <p className="text-paragraphsmall font-thin">{textContent}</p>
            </span>
          ))}
        </div>
      </div>
    </div>
  );
};

export default RightToLeftBannerLight;
